using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WeaponShop.Infrastructure;

#nullable disable

namespace WeaponShop.Infrastructure.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401124500_AddOrderAuditAndNotifications")]
    public partial class AddOrderAuditAndNotifications : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "purchase_request_audits" (
                    "audit_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "request_id" integer NOT NULL,
                    "from_status" integer NOT NULL,
                    "to_status" integer NOT NULL,
                    "action_name" character varying(200) NOT NULL,
                    "actor_user_id" text NOT NULL,
                    "actor_name" character varying(200) NOT NULL,
                    "actor_role" character varying(50) NOT NULL,
                    "occurred_at_utc" timestamp with time zone NOT NULL,
                    "notes" text,
                    CONSTRAINT "fk_purchase_request_audits_order" FOREIGN KEY ("request_id")
                        REFERENCES "purchase_requests" ("request_id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_indexes
                        WHERE schemaname = 'public'
                          AND indexname = 'ix_purchase_request_audits_request_id_occurred_at_utc'
                    ) THEN
                        CREATE INDEX "ix_purchase_request_audits_request_id_occurred_at_utc"
                            ON "purchase_request_audits" ("request_id", "occurred_at_utc");
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "user_notifications" (
                    "notification_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "user_id" text NOT NULL,
                    "title" character varying(200) NOT NULL,
                    "message" character varying(1000) NOT NULL,
                    "created_at_utc" timestamp with time zone NOT NULL,
                    "is_read" boolean NOT NULL,
                    CONSTRAINT "fk_user_notifications_user" FOREIGN KEY ("user_id")
                        REFERENCES "users" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_indexes
                        WHERE schemaname = 'public'
                          AND indexname = 'ix_user_notifications_user_id_created_at_utc'
                    ) THEN
                        CREATE INDEX "ix_user_notifications_user_id_created_at_utc"
                            ON "user_notifications" ("user_id", "created_at_utc");
                    END IF;
                END $$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "purchase_request_audits";""");
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "user_notifications";""");
        }
    }
}
